### ISSUE TITLE
Error to fix on script upstream 

### ISSUE THREAD

**Issue by JayB-Kayode** [JayB-Kayode/My-Scripts#1]
getting this error when running the script 
/home/jb/bin/upstream.sh: line 12: syntax error near unexpected token `then'
/home/jb/bin/upstream.sh: line 12: `if [[ -z $(grep upstream .git/config) ]] then'

**Comment by lcabrini** [comment]
You need a ; between ]] and then

Or you could put then on a new line and you don't need the ;.
